### ISSUE TITLE
invalid escape sequence in doc strings

### ISSUE THREAD

**Issue by ptoche** [unexploredtest/neural-networks-and-deep-learning#4]
`"invalid escape sequence in doc strings"` 

To fix the issue, I edited the docstring to something like:

    def cost_derivative(self, output_activations, y):
        """Return the vector of partial derivatives 
        .. math::
        \\partial C_x / \\partial 
        a for the output activations."""

FYI, I ran the code with:

      import os
      os.chdir("/pathto/neural-networks-and-deep-learning/src")
      exec(open("network.py").read())
    
I've only tested "network.py": It ran fine! Thanks.

**Comment by unexploredtest** [comment]
Thanks for the feedback!
Can't reproduce, is the error resulted from running the network?

**Comment by ptoche** [comment]
Sorry that was vague: I'm using "Python 3.12.3" locally. I believe there have been changes in what you can write inside docstrings. See: https://stackoverflow.com/questions/52335970/how-to-fix-syntaxwarning-invalid-escape-sequence-in-python

**Comment by unexploredtest** [comment]
Okay I see, unfortunately support isn't possible for Python 3.11.* and upwards because Theano is out of support and doesn't support newer versions of Numpy.

**Comment by ptoche** [comment]
Oh I see, thank you!
