### ISSUE TITLE
requiring about a new bug

### ISSUE THREAD

**Issue by Iverson-cui** [unexploredtest/neural-networks-and-deep-learning#5]
Excuse me. I ran ur code and met a nw bug. I don't know if I have done something wrong.
![image](https://github.com/user-attachments/assets/b82de60e-6e36-4823-a07f-968768c34c1a)
When I read the data, this error comes up: 'ascii' codec can't decode byte 0x90 in position 614: ordinal not in range(128)
If anyone know what have caused this!

**Comment by unexploredtest** [comment]
Yeah the code doesn't match, probably ran the wrong code but I think you've figured it out as you've already closed the issue.
